sed -i -e 's/Ġ/𐩶/g' csai.txt
sed -i -e 's/ġ/𐩶/g' csai.txt
sed -i -e 's/ś/𐩯/g' csai.txt
sed -i -e 's/š/𐩦/g' csai.txt
sed -i -e 's/ʾ/𐩱/g' csai.txt
sed -i -e 's/ʿ/𐩲/g' csai.txt
sed -i -e 's/Ḍ/𐩳/g' csai.txt
sed -i -e 's/ḍ/𐩳/g' csai.txt
sed -i -e 's/Ḏ/𐩹/g' csai.txt
sed -i -e 's/ḏ/𐩹/g' csai.txt
sed -i -e 's/Ḥ/𐩢/g' csai.txt
sed -i -e 's/ḥ/𐩢/g' csai.txt
sed -i -e 's/Ḫ/𐩭/g' csai.txt
sed -i -e 's/ḫ/𐩭/g' csai.txt
sed -i -e 's/Ṣ/𐩮/g' csai.txt
sed -i -e 's/ṣ/𐩮/g' csai.txt
sed -i -e 's/Ṭ/𐩷/g' csai.txt
sed -i -e 's/ṭ/𐩷/g' csai.txt
sed -i -e 's/Ṯ/𐩻/g' csai.txt
sed -i -e 's/ṯ/𐩻/g' csai.txt
sed -i -e 's/Ẓ/𐩼/g' csai.txt
sed -i -e 's/ẓ/𐩼/g' csai.txt
sed -i -e 's/	ġ/𐩶/g' csai.txt
sed -i -e 's/B/𐩨/g' csai.txt
sed -i -e 's/D/𐩵/g' csai.txt
sed -i -e 's/F/𐩰/g' csai.txt
sed -i -e 's/G/𐩴/g' csai.txt
sed -i -e 's/H/𐩠/g' csai.txt
sed -i -e 's/K/𐩫/g' csai.txt
sed -i -e 's/L/𐩡/g' csai.txt
sed -i -e 's/M/𐩣/g' csai.txt
sed -i -e 's/N/𐩬/g' csai.txt
sed -i -e 's/Q/𐩤/g' csai.txt
sed -i -e 's/R/𐩧/g' csai.txt
sed -i -e 's/S/𐩪/g' csai.txt
sed -i -e 's/T/𐩩/g' csai.txt
sed -i -e 's/W/𐩥/g' csai.txt
sed -i -e 's/Y/𐩺/g' csai.txt
sed -i -e 's/Z/𐩸/g' csai.txt
sed -i -e 's/b/𐩨/g' csai.txt
sed -i -e 's/d/𐩵/g' csai.txt
sed -i -e 's/f/𐩰/g' csai.txt
sed -i -e 's/g/𐩴/g' csai.txt
sed -i -e 's/h/𐩠/g' csai.txt
sed -i -e 's/k/𐩫/g' csai.txt
sed -i -e 's/l/𐩡/g' csai.txt
sed -i -e 's/m/𐩣/g' csai.txt
sed -i -e 's/n/𐩬/g' csai.txt
sed -i -e 's/q/𐩤/g' csai.txt
sed -i -e 's/r/𐩧/g' csai.txt
sed -i -e 's/s²/𐩦/g' csai.txt
sed -i -e 's/s³/𐩯/g' csai.txt
sed -i -e 's/s¹/𐩪/g' csai.txt
sed -i -e 's/s/𐩪/g' csai.txt
sed -i -e 's/t/𐩩/g' csai.txt
sed -i -e 's/w/𐩥/g' csai.txt
sed -i -e 's/y/𐩺/g' csai.txt
sed -i -e 's/z/𐩸/g' csai.txt
